name: Build mGBA with Python bindings for macOS ARM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout mGBA source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake qt@5 python@3.10 swig

    - name: Install Python dependencies
      run: |
        python3.10 -m ensurepip
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip install cffi

    - name: Configure build
      run: |
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_CORE=ON \
          -DBUILD_PYTHON=ON \
          -DPYTHON_EXECUTABLE=$(which python3.10)

    - name: Build mGBA and bindings
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)

    - name: Package output
      run: |
        mkdir -p output/mgba
        cp build/libmgba*.dylib output/ || true

        # Adjust this path as needed if Python version/macOS changes in future runners
        cp build/python/lib.macosx-14-arm64-cpython-310/mgba/_pylib*.so output/mgba/ || true
        cp -r src/platform/python/mgba/* output/mgba/ || true

        echo "Listing output/mgba directory:"
        ls -l output/mgba || true

        echo "Listing output directory:"
        ls -l output || true

        tar -czvf output/mgba-macos-arm64-python.tar.gz -C output .

        echo "Output tar file path:"
        echo "$(pwd)/output/mgba-macos-arm64-python.tar.gz"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mgba-macos-arm64-python
        path: output/mgba-macos-arm64-python.tar.gz
